name: issue-workflow
on:
  issues:
    types: [opened]

jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo issue job test
    - name: step2
      run: echo github action
       