name: needs
on: push


# 여러개의 잡을 선언하면 기본적으로 병렬로 실행. needs를 사용해서 job 의존관계를 만들어줄 수 있다. 
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps: 
    - name: echo
      run: echo "job1 done"

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - name: echo
      run: echo "job2 done"

  job3:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: |
        echo "job3 fail"
        exit 1

  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    steps:
    - name: echo
      run: echo "job4 done"