name: issu-notify
on: 
  issues: 
    types: [opened]



jobs:
  get-keyword:
    runs-on: ubuntu-latest

    steps:

    - name: checkout #github repo code를 사용하기 위해
      uses: actions/checkout@v4

    - name: get keyword
      id: get-keyword
      run: |
        echo level=Undefined >> $GITHUB_OUTPUT
        
        keywords=$(cat keyword-list.txt)
        for keyword in $keywords; do
          if [[ "${{ github.event.issue.title }}" =~ "$keyword" ]]; then
            echo level=$keyword >> $GITHUB_OUTPUT
          fi
        done  
      
    - name: 
      run: |
        echo ${{ steps.get-keyword.outputs.level }}
