 name: pull-request-workflow
 on: 
  pull_request:
    types: [opened] #pull request가 open될때만 이벤트가 트리거되고, pull request 보낸 브랜치에 변경사항이 있을 때는 트리거되지 않게.

 jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps: 
    - name: step1
      run: echo hello world
    - name: step2 
      run: |
        echo hello world
        echo github action 
        